[package]
name = "bandit-types"
version.workspace = true
edition.workspace = true
publish = false

[package.metadata.cargo-udeps.ignore]
# Only used in docs
normal = ["katexit"]

[dependencies]
clonelet.workspace = true
derive_more = { workspace = true, features = ["constructor"] }
futures.workspace = true
katexit.workspace = true
pretty.workspace = true
tokio = { workspace = true, features = ["sync"] }
