[package]
name = "bandit-parser"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
bandit-term.workspace = true
logos.workspace = true
winnow.workspace= true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "lexer"
harness = false
