[package]
name = "bandit-compiler"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
bandit-parser.workspace = true
bandit-term.workspace = true
winnow.workspace = true
clap = { workspace = true, features = ["derive"] }
anyhow.workspace = true